# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\qtpj\uifin\error.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QRect, QCoreApplication, QEvent
from PyQt5.QtWidgets import QApplication, QDesktopWidget, QWidget, QPushButton, QMainWindow
from PyQt5.QtGui import QMouseEvent, QCursor


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.offset = None

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(800, 500))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)

        self.label.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.label.setMinimumSize(QtCore.QSize(800, 500))
        self.label.setMaximumSize(QtCore.QSize(800, 500))

        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:/AdobePJ/XD/ZOSC UI/exclude/error.png"))
        self.label.setObjectName("label")

        """yes button"""
        self.btn_yes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_yes.setGeometry(QtCore.QRect(550, 420, 180, 60))
        self.btn_yes.setObjectName("btn_yes")
        self.btn_yes.setStyleSheet(
            '''
            QPushButton{image:url(D:/AdobePJ/XD/ZOSC UI/button/normal/btn.yes.png); border:0px;}
            QPushButton:hover{image:url(D:/AdobePJ/XD/ZOSC UI/button/active/btn.yes.active.png); border:0px;}
            '''
        )

        self.btn_yes.clicked.connect(QCoreApplication.instance().quit)
        """end"""

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#import error_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
