# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\qtpj\uifin\zosc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtCore import Qt, QRect, QCoreApplication, QEvent
from PyQt5.QtWidgets import QApplication, QDesktopWidget, QWidget, QPushButton, QMainWindow, QDialog
from PyQt5.QtGui import QMouseEvent, QCursor

class settingWindow(QDialog):
    def __init__(self, parent):
        super(settingWindow, self).__init__(parent)
            
    def setupUi(self, settingWindow):
        settingWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.offset = None

        settingWindow.setObjectName("settingWindow")
        settingWindow.resize(600, 500)
        settingWindow.setMinimumSize(QtCore.QSize(600, 500))
        settingWindow.setMaximumSize(QtCore.QSize(600, 500))

        self.centralwidget = QtWidgets.QWidget(settingWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 600, 500))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("D:/AdobePJ/XD/ZOSC UI/exclude/Setting.png"))
        self.background.setObjectName("background")

        self.dot = QtWidgets.QLabel(self.centralwidget)
        self.dot.setGeometry(QtCore.QRect(70, 130, 21, 61))
        self.dot.setText("")
        self.dot.setPixmap(QtGui.QPixmap("D:/AdobePJ/XD/ZOSC UI/elements/•.png"))
        self.dot.setObjectName("dot")

        """close button"""
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(535, 7, 55, 25))
        self.btn_close.setObjectName("btn_close")
        self.btn_close.setStyleSheet(
            '''
            QPushButton{image:url(D:/AdobePJ/XD/ZOSC UI/button/normal/btn.close.png); border:0px;}
            QPushButton:hover{image:url(D:/AdobePJ/XD/ZOSC UI/button/active/btn.close.active.png); border:0px;}
            '''
        )

        self.btn_close.clicked.connect(QCoreApplication.instance().quit)
        """end"""

        self.btn_info = QtWidgets.QPushButton(self.centralwidget)
        self.btn_info.setGeometry(QtCore.QRect(500, 440, 41, 23))
        self.btn_info.setObjectName("btn_info")
        self.btn_info.setStyleSheet(
            '''
            QPushButton{image:url(D:/AdobePJ/XD/ZOSC UI/button/normal/info.png); border:0px;}
            QPushButton:hover{image:url(D:/AdobePJ/XD/ZOSC UI/button/active/info.active.png); border:0px;}
            '''
        )

        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(70, 143, 170, 40))
        self.btn_reset.setObjectName("btn_reset")
        self.btn_reset.setStyleSheet(
            '''
            QPushButton{image:url(D:/AdobePJ/XD/ZOSC UI/button/normal/user.reset.png); border:0px;}
            QPushButton:hover{image:url(D:/AdobePJ/XD/ZOSC UI/button/active/user.reset.active.png); border:0px;}
            '''
        )

        settingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(settingWindow)
        QtCore.QMetaObject.connectSlotsByName(settingWindow)

    def retranslateUi(self, settingWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.offset = None

        self.btn_setting.clicked.connect(self.open_setting)

    def open_setting(self):
        settingWindow(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZOOM SCHEDULER"))

    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            self.m_flag = True
            self.m_Position=event.globalPos()-self.pos()
            event.accept()
            self.setCursor(QCursor(Qt.OpenHandCursor))

    def mouseMoveEvent(self, QMouseEvent):
        if Qt.LeftButton and self.m_flag:
            self.move(QMouseEvent.globalPos()-self.m_Position)
            QMouseEvent.accept()

    def mouseReleaseEvent(self, QMouseEvent):
        self.m_flag = False
        self.setCursor(QCursor(Qt.ArrowCursor))
        
    def setupUi(self, MainWindow):
        MainWindow.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowMinimizeButtonHint)
        MainWindow.setMinimumSize(1100, 650)
        MainWindow.setMaximumSize(QtCore.QSize(1100, 650))

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\qtpj\\uifin\\../../AdobePJ/XD/ZOSC UI/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        MainWindow.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(-10, -10, 1121, 61))
        self.title.setText("")
        self.title.setPixmap(QtGui.QPixmap("D:/AdobePJ/XD/ZOSC UI/elements/zosc.png"))
        self.title.setObjectName("title")

        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 40, 1111, 611))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("D:/AdobePJ/XD/ZOSC UI/landscape/Main.png"))
        self.background.setObjectName("background")

        """run button"""
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run.setGeometry(QtCore.QRect(840, 570, 171, 71))
        self.btn_run.setStyleSheet(
            '''
            QPushButton{image:url(D:/AdobePJ/XD/ZOSC UI/button/normal/btn.run.png); border:0px;}
            QPushButton:hover{image:url(D:/AdobePJ/XD/ZOSC UI/button/active/btn.run.active.png); border:0px;}
            '''
        )
        font = QtGui.QFont()
        font.setFamily("AppleSDGothicNeoB00")
        font.setPointSize(28)
        self.btn_run.setFont(font)
        self.btn_run.setObjectName("btn_run")
        """end"""

        """notice button"""
        self.btn_notice = QtWidgets.QPushButton(self.centralwidget)
        self.btn_notice.setGeometry(QtCore.QRect(15, 80, 101, 71))
        self.btn_notice.setStyleSheet(
            '''
            QPushButton{image:url(D:/AdobePJ/XD/ZOSC UI/button/normal/notice.refresh.png); border:0px;}
            QPushButton:hover{image:url(D:/AdobePJ/XD/ZOSC UI/button/active/notice.refresh.active.png); border:0px;}
            '''
        )
        font = QtGui.QFont()
        font.setFamily("AppleSDGothicNeoB00")
        self.btn_notice.setFont(font)
        self.btn_notice.setObjectName("btn_notice")
        """end"""

        """setting button"""
        self.btn_setting = QtWidgets.QPushButton(self.centralwidget)
        self.btn_setting.setGeometry(QtCore.QRect(10, 5, 30, 30))
        self.btn_setting.setStyleSheet(
            '''
            QPushButton{image:url(D:/AdobePJ/XD/ZOSC UI/button/normal/btn.setting.png); border:0px;}
            QPushButton:hover{image:url(D:/AdobePJ/XD/ZOSC UI/button/active/btn.setting.active.png); border:0px;}
            '''
        )
        self.btn_setting.setObjectName("btn_setting")
        """end"""

        """hide button"""
        self.btn_hide = QtWidgets.QPushButton(self.centralwidget)
        self.btn_hide.setGeometry(QtCore.QRect(990, 10, 40, 20))
        self.btn_hide.setStyleSheet(
            '''
            QPushButton{image:url(D:/AdobePJ/XD/ZOSC UI/button/normal/line.hide.png); border:0px;}
            QPushButton:hover{image:url(D:/AdobePJ/XD/ZOSC UI/button/active/line.hide.active.png); border:0px;}
            ''' 
        )
        self.btn_hide.setObjectName("btn_hide")

        self.btn_hide.clicked.connect(MainWindow.showMinimized)
        """end"""

        """close button"""
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(1045, 10, 40, 20))
        self.btn_close.setStyleSheet(
            '''
            QPushButton{image:url(D:/AdobePJ/XD/ZOSC UI/button/normal/btn.close.png); border:0px;}
            QPushButton:hover{image:url(D:/AdobePJ/XD/ZOSC UI/button/active/btn.close.active.png); border:0px;}
            '''
        )
        self.btn_close.setObjectName("btn_close")

        self.btn_close.clicked.connect(QCoreApplication.instance().quit)
        """end"""
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
#import zosc_resource_rc

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())